---

- block:
    - when: mongodb_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - when: mongodb_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"
  tags:
    - setup-all
    - setup-mongodb
    - install-all
    - install-mongodb

- block:
    - when: mongodb_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/import.yml"
  tags:
    - import-mongodb

- block:
    - when: not mongodb_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
  tags:
    - setup-all
    - setup-mongodb
