---

- name: Fail if required MongoDB settings not defined
  ansible.builtin.fail:
    msg: >
      You need to define a required configuration setting (`{{ item }}`).
  when: "vars[item] == ''"
  with_items:
    - mongodb_identifier
    - mongodb_uid
    - mongodb_gid
    - mongodb_container_network
